spring:
  datasource:
    url: jdbc:oracle:thin:@${DB_TNS_NAME:fs3_tp}?TNS_ADMIN=${TNS_ADMIN_PATH:./wallet}
    username: ${DB_USERNAME:ADMIN}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.OracleDialect

  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/oracle
